const ACTION_TYPES = {
  GET_REVIEWS_REQUEST: 'GET_REVIEWS_REQUEST',
  GET_REVIEWS_SUCCESS: 'GET_REVIEWS_SUCCESS',
  GET_REVIEWS_ERROR: 'GET_REVIEWS_ERROR',

  GET_QUESTIONS_REQUEST: 'GET_QUESTIONS_REQUEST',
  GET_QUESTIONS_SUCCESS: 'GET_QUESTIONS_SUCCES',
  GET_QUESTIONS_ERROR: 'GET_QUESTIONS_ERROR'
}

export default ACTION_TYPES
